### ISSUE TITLE
Sounds GUI not producing any sounds when clicking on the heads

### ISSUE THREAD

**Issue by RedSparr0w** [DaniFoldi/BungeeGUI#76]
No sounds produced by sounds GUI in example config

BungeeCord version: `git:BungeeCord-Bootstrap:1.17-R0.1-SNAPSHOT:ad50fc9:1585`
Protocolize version: `protocolize-plugin version 1.7.0-SNAPSHOT:605`
BungeeGUI version: `1.2.6`
Minecraft client: `v1.16.5`

**Comment by RedSparr0w** [comment]
Good point 😅
Was with 1.16.5

**Comment by DaniFoldi** [comment]
Oh yes, the config file was wrong. Protocolize has their mappings automatically generated, and in some cases the naming is inconsistent with the built-in ones, so I wrote a custom function to send sounds, but forgot to update the default config. Will merge soon.
