### ISSUE TITLE
BungeeGUI wont load

### ISSUE THREAD

**Issue by ItzRonaldMLG** [DaniFoldi/BungeeGUI#85]
Hello, 
Latest Bungeecord version: 1.17-R0.1-snapshot:bda1605:1598
Latest Protocolized: 1.17.1-snapshot:689

Error1: https://pastebin.com/j8L4BaRa (Startup)
Error2: https://pastebin.com/i2H76jc3 (Loaded)

PS: Protocolized it getting a recode soon, i think you knew already but just a reminder

**Comment by DaniFoldi** [comment]
Version 2.0.0 fixes this issue
